export const TYPES = {
  // Repositories
  AccountsRepository: Symbol.for("AccountsRepository"),
  SessionsRepository: Symbol.for("SessionsRepository"),
  VerificationsRepository: Symbol.for("VerificationsRepository"),
  ProfilesRepository: Symbol.for("ProfilesRepository"),
  LeagueTypesRepository: Symbol.for("LeagueTypesRepository"),
  LeaguesRepository: Symbol.for("LeaguesRepository"),
  LeagueMembersRepository: Symbol.for("LeagueMembersRepository"),
  LeagueInvitesRepository: Symbol.for("LeagueInvitesRepository"),
  PhasesRepository: Symbol.for("PhasesRepository"),
  PhaseTemplatesRepository: Symbol.for("PhaseTemplatesRepository"),
  DataSourcesRepository: Symbol.for("DataSourcesRepository"),
  SportLeaguesRepository: Symbol.for("SportLeaguesRepository"),
  SeasonsRepository: Symbol.for("SeasonsRepository"),
  UsersRepository: Symbol.for("UsersRepository"),
  TeamsRepository: Symbol.for("TeamsRepository"),
  EventsRepository: Symbol.for("EventsRepository"),
  OddsRepository: Symbol.for("OddsRepository"),
  SportsbooksRepository: Symbol.for("SportsbooksRepository"),
  LiveScoresRepository: Symbol.for("LiveScoresRepository"),
  OutcomesRepository: Symbol.for("OutcomesRepository"),

  // Services
  ProfilesService: Symbol.for("ProfilesService"),
  LeagueTypesService: Symbol.for("LeagueTypesService"),
  LeaguesService: Symbol.for("LeaguesService"),
  LeagueMembersService: Symbol.for("LeagueMembersService"),
  LeagueInvitesService: Symbol.for("LeagueInvitesService"),
  PhasesService: Symbol.for("PhasesService"),
  PhaseTemplatesService: Symbol.for("PhaseTemplatesService"),
  UsersService: Symbol.for("UsersService"),
  DataSourcesService: Symbol.for("DataSourcesService"),
  SportLeaguesService: Symbol.for("SportLeaguesService"),
  SeasonsService: Symbol.for("SeasonsService"),
  TeamsService: Symbol.for("TeamsService"),
  EventsService: Symbol.for("EventsService"),

  // Util Services
  LeaguesUtilService: Symbol.for("LeaguesUtilService"),
  SeasonsUtilService: Symbol.for("SeasonsUtilService"),

  // Query Services
  LeaguesQueryService: Symbol.for("LeaguesQueryService"),
  LeagueTypesQueryService: Symbol.for("LeagueTypesQueryService"),
  LeagueMembersQueryService: Symbol.for("LeagueMembersQueryService"),
  UsersQueryService: Symbol.for("UsersQueryService"),
  LeagueInvitesQueryService: Symbol.for("LeagueInvitesQueryService"),
  ProfilesQueryService: Symbol.for("ProfilesQueryService"),
  PhaseTemplatesQueryService: Symbol.for("PhaseTemplatesQueryService"),
  PhasesQueryService: Symbol.for("PhasesQueryService"),
  SeasonsQueryService: Symbol.for("SeasonsQueryService"),
  DataSourcesQueryService: Symbol.for("DataSourcesQueryService"),
  SportLeaguesQueryService: Symbol.for("SportLeaguesQueryService"),
  TeamsQueryService: Symbol.for("TeamsQueryService"),
  EventsQueryService: Symbol.for("EventsQueryService"),
  OddsQueryService: Symbol.for("OddsQueryService"),
  SportsbooksQueryService: Symbol.for("SportsbooksQueryService"),
  LiveScoresQueryService: Symbol.for("LiveScoresQueryService"),
  OutcomesQueryService: Symbol.for("OutcomesQueryService"),

  // Mutation Services
  AccountsMutationService: Symbol.for("AccountsMutationService"),
  SessionsMutationService: Symbol.for("SessionsMutationService"),
  VerificationsMutationService: Symbol.for("VerificationsMutationService"),
  LeagueMembersMutationService: Symbol.for("LeagueMembersMutationService"),
  UsersMutationService: Symbol.for("UsersMutationService"),
  LeagueInvitesMutationService: Symbol.for("LeagueInvitesMutationService"),
  ProfilesMutationService: Symbol.for("ProfilesMutationService"),
  LeaguesMutationService: Symbol.for("LeaguesMutationService"),
  PhaseTemplatesMutationService: Symbol.for("PhaseTemplatesMutationService"),
  PhasesMutationService: Symbol.for("PhasesMutationService"),
  SeasonsMutationService: Symbol.for("SeasonsMutationService"),
  DataSourcesMutationService: Symbol.for("DataSourcesMutationService"),
  SportLeaguesMutationService: Symbol.for("SportLeaguesMutationService"),
  TeamsMutationService: Symbol.for("TeamsMutationService"),
  EventsMutationService: Symbol.for("EventsMutationService"),
  OddsMutationService: Symbol.for("OddsMutationService"),
  SportsbooksMutationService: Symbol.for("SportsbooksMutationService"),
  LiveScoresMutationService: Symbol.for("LiveScoresMutationService"),
  OutcomesMutationService: Symbol.for("OutcomesMutationService"),

  // External Services
  EspnService: Symbol.for("EspnService"),
};
