project_name: "picksleagues-api"
default_status: "To Do"
statuses: ["To Do", "In Progress", "Done"]
labels: []
milestones: []
date_format: yyyy-mm-dd
max_column_width: 20
auto_open_browser: true
default_port: 6421
remote_operations: true
auto_commit: true
zero_padded_ids: 3
